# nginx proxy address - http://172.17.0.1:8055

name: directus
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: directus/directus:latest
    container_name: directus-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:8055:8055'
    volumes:
      - './rootfs/data/directus:/data'
    networks:
      - directus

networks:
  directus:
    name: directus
    external: false
